### ISSUE TITLE
telegram: can't remove chat owner (400)

### ISSUE THREAD

**Issue by YogiPristiawan** [teknologi-umum/captcha#33]
Ketika grup dalam mode `underattack`, dan admin ingin menambahkan anggota baru, error muncul:
![image](https://user-images.githubusercontent.com/72334350/194758838-9be16653-c8b0-45bc-8f58-b023d2f31447.png)

**Comment by aldy505** [comment]
emang ngga boleh tambahin orang selama underattack

**Comment by YogiPristiawan** [comment]
oalah kirain bug :D
